[package]
name = "voxel_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glutin = "0.29.1"
# glfw = {version = "0.53.0", features = ["image"]}
image = "*"
nalgebra = "0.32.3"
